### ISSUE TITLE
const robot_name

### ISSUE THREAD

**Issue by wilhelmtell** [exercism/xcpp#48] opened 2015-07-16 22:47 UTC
I realized robot-name tests repeatedly start with

```
const robot_name::robot robot;
// ..
```

I think this is a hint for a design flaw, and being an exercise, encourages a bad idea.

The line instantiates a const `robot_name::robot` object using the default constructor. The compiler refuses to leave the object in an unspecified state, because the object is qualified `const`, and thereby looks for a user-provided default constructor.

To illustrate, consider:

```
int const i;
```

This won't compile. `i` has unspecified state, and its value may not change -- so what good is it? In contrast,

```
int const i{};
```

is fine. `i` is zeroed-out, left in a known determinate state, and that can be const and useful.

Being able to skip the work of leaving data in a specified state is a good thing. If you provide a non-trivial default constructor, the kind that would allow for that line above to compile, then you forbid fast instantiations of the object. To motivate, consider:

```
robot_name robot;
std::cin >> robot;
// ...
```

We work hard to construct `robot` when we know full well it's hard work for nothing. You may argue the problem is with `std::cin` being of a poor design in a way, not being functional-friendly, and I agree. But unfortunately it's not going to change soon, for all I can see, and right now it encourages default-construction to be fast.

Or, another case:

```
std::vector<robot_name::robot> robots(100000);
std::generate(begin(robots), end(robots), mutate_optimus_prime);
```

Here, creating a default robot is not so cheap, compared with a robot with no user-provided default constructor. We make a hundred thousand of these, and a moment later overwrite them with new ones. Instantiating the vector should be quick, because we don't care about the values -- we're going to change them in a moment.

You might argue this is a bad example; that we should use `std::generate_n()` with a `std::back_inserter_iterator<>` and a zero-sized `std::vector<>`, so the vector grows as needed and immediately with the object we want, not with unnecessary intermediates. That's fair enough. But one may also argue that the trap of the hidden performance price you pay with `std::generate()` and a pre-sized vector ain't cool either.

Also,

```
struct starship {
private:
  robot_name::robot robot;
};
```

The `strarship` type *could* be a wonderful value type -- except it's flawed by `robot` not allowing it to instantiate quickly. It's like the design of `robot` is intrusive, like a virus a politician would say, silently invading other objects that would like to reuse it.

And besides, when you see the line

```
robot_name::robot const robot;
```

you intuitively ask questions. "So... this is like `int i`, data with junk inside, and I can't change it?" and then you spend time looking at the class, and oh, right, it has a user-provided default constructor. Duh.

If the constructor is `=default`-ed or not provided at all then that line won't compile, and no one starts suspecting and asking questions.

This reminds me of a similar issue I remember encountering in the [Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) library, where they (used to?) provide a non-trivial default constructor for matrices. There, I've reported the issue to them, and IIRC the trouble was that the library exists since C++03, and, well, changing this sort of thing breaks backwards compatibility. And that's a big no-no for a popular library. The library is slower because of a technical debt that's hard to flatten out now.

The point I'm trying to make is that a line like

```
T const t;
```

raises eyebrows, and a user-provided default constructor allows for it. That there is no consensus on a sensible default for the state of an object, but users will always be either happy with or relying on fast construction. That exercism is a tool that spreads example, and bad example is worse than no example.

Okay maybe I'm going too far and taking the whole thing too seriously. Still hey let's remove the user-provided default ctor k? k? mm? maybe?

**Comment by kytrinyx** [comment] 2015-07-17 04:33
> Okay maybe I'm going too far and taking the whole thing too seriously.

:) I'm not sure, one of my favorite parts of exercism is going slightly overboard with these sorts of things. That said, I don't write C++, so I'm going to have to defer to @LegalizeAdulthood and others who _do_ write it.

**Comment by LegalizeAdulthood** [comment] 2015-07-20 18:04
This is by design. I wrote the tests this way to say that `name` is a `const` method, that the name of the robot is decided at the time of `robot` construction and remains unchanged until `reset` is called and that `reset` is a modifying method.

I don't see any more straightforward way of expressing this in the test.  I don't understand your objection to a default constructor.

**Comment by LegalizeAdulthood** [comment] 2015-08-20 20:14
I'm closing this issue because a month has gone by and no further information has been provided.

**Closed by LegalizeAdulthood** 2015-08-20 20:14 UTC
