### ISSUE TITLE
I have to hack every c++ test case because of `<<` operator

### ISSUE THREAD

**Issue by Skarlso** [exercism/xcpp#111] opened 2017-01-28 08:39 UTC
Hi. 

So, every test case I'm running throws this error into my face:

```bash
/usr/local/Cellar/boost/1.62.0/include/boost/test/tools/detail/print_helper.hpp:47:5: error: static_assert failed "Type has to implement operator<< to be printable"
    BOOST_STATIC_ASSERT_MSG( (boost::has_left_shift<std::ostream,T>::value),
```

I can see that there is a hack there called `#include "require_equal_containers.h"` but it's not working. 

Is there a solution for this to make it work or build it with some other version of boost? Or anything? It's becoming rather tedious to always delete it, and change it to `BOOST_EQUAL`.

Thanks.

**Comment by Skarlso** [comment] 2017-01-28 08:43
Okay, so I've got it, I think... 

I was using plain `cmake ..` instead of `cmake -G Xcode ..` because I thought it would detect my operating system. Afterwards, the case is, that I don't have `make` command anymore, so I have to use `cmake --build .`. Is this the intended usage?

**Comment by Skarlso** [comment] 2017-01-28 09:32
Nope, still says the same thing ( I just had a typo. ). So `cmake --build .` and using `-G Xcode` didn't help either.

**Comment by patricksjackson** [comment] 2017-01-29 19:38
Those are two different issues.

Using `cmake` is one. If you use `cmake -G Xcode ..` it will generate an Xcode project, and you will need to use Xcode to build it. I'm not sure if Unix Makefiles is the default generator or Mac, but calling it with `cmake -G "Unix Makefiles" ..` would select it.

The Boost issue is something that needs a fix in the repo. The `require_equal_containers` workaround breaks with newer versions of Boost for reasons I'm not entirely sure about. I'm planning to sort out a fix soon I've just been swamped with real work.

**Comment by Skarlso** [comment] 2017-01-29 19:57
Thanks for the response @patricksjackson. Sorry, I did not denote that I'm actually using osx here. So I need the xcode stuff. Also, after that I'm building with `cmake --build . ` thus it should be operating system agnostic.

**Comment by sunzenshen** [comment] 2017-01-30 05:59
I'm also affected by the Boost require_equal_containers issue as well, so let me know if I can help with reproduction or general triage.

**Comment by sunzenshen** [comment] 2017-02-01 04:56
@patricksjackson I found this post about the operator << override, and the proposed solution variant seems to work on my end:

http://bcreane.tumblr.com/post/148999817295/boost-unit-test-compilation-error

That is, for the `require_equal_containers.h` block in `#if BOOST_VERSION >= 105900`, this replacement seems to resolve the issue for std::pair:
```CPP
// teach Boost.Test how to print std::pair<K,V>
template <class F, class S>
struct print_log_value< ::std::pair<F, S> > {
  void operator()(::std::ostream & os, ::std::pair<F, S> const & p ) {
    os << "([" << p.first << "], [" << p.second << "])";
  }
};
} // namespace tt_detail
} // namespace test_tools
} // namespace boost
```

However, if the issue came as a result of an updated boost, I'm not sure of which version the issue was introduced.

**Comment by sunzenshen** [comment] 2017-02-01 05:25
@Skarlso @patricksjackson I have created a cleaned-up gist with a modified version of require_equal_containers.h here:
https://gist.github.com/sunzenshen/c1fb6aa1796d778ac50aa6c98063558b

Some unanswered questions:

- When and why did the boost container overrides break?
- Why does this signature work while the existing implementation does not? 

Sample test cases:
```CPP
BOOST_AUTO_TEST_CASE(vector_overrides)
{
    std::vector<int> a {23, 43};
    std::vector<int> b {23, 43};
    BOOST_REQUIRE_EQUAL(a, b);
}
```

```CPP
BOOST_AUTO_TEST_CASE(pair_overrides)
{
    BOOST_REQUIRE_EQUAL(std::make_pair(1, 3), std::make_pair(1, 3));
}
```

**Comment by sunzenshen** [comment] 2017-02-01 05:35
After the fact, just noticed this alternative fix implementation:
https://github.com/exercism/xcpp/pull/110

@liquidcore7: Any thoughts? I figured that I should give you a heads up since you took the time to submit a pull request.

I understand that individually extracting the items of std::pair removes the dependency on `require_equal_containers`, but I'm not quite convinced that it's the idiomatic way to resolve this boost dependency.

**Comment by Skarlso** [comment] 2017-02-01 12:44
@sunzenshen Also, @liquidcore7's pull is only about one test while I'm constantly experiencing the problem. Which means it's probably because of boost version 1.63 update. *Probably*.

**Comment by patricksjackson** [comment] 2017-02-02 23:39
I _think_ the issue has been there since Boost 1.60 or 1.61 at least, but I'm not sure. Presumably it worked at least with Boost 1.59.

I am somewhat concerned about fixing it the idiomatic way since they have already broken it once (or possibly twice?). It would be relatively easy to just replace it with a set of helper functions that use the basic tests to check for equality. That would give us a single implementation that would work with all Boost versions, and we'd mostly avoid having to re-write the 6 test suites using it.

**Comment by patricksjackson** [comment] 2017-04-16 21:46
Pinging this thread. I opened a PR with a fix for this issue, though it breaks compatibility with Boost<1.59

**Comment by patricksjackson** [comment] 2017-04-23 16:46
Merged in the fix for this in #118

**Closed by patricksjackson** 2017-04-23 16:46 UTC

**Comment by Skarlso** [comment] 2017-04-24 15:44
Eyyy, awesome. Thanks for taking care of this. Sorry for the lack of replies... My daughter was just born recently. :) Takes up all my free time. :)

**Comment by patricksjackson** [comment] 2017-04-24 16:30
No problem, I've been quite busy myself which is why it took me so long to get to it. Congrats on the kid :)
